'use strict';

/* Controllers */
var myApp = angular.module('myApp', []);

var session = new QiSession();

myApp.controller('myCtrl', ['$scope', function ($scope) {
  $scope.sentence = "Generated by Raccoon team";

  
// get variable template  
%variable%

        
// allow to raise event from web page ng-click
$scope.raiseEvent  = function(id, value) 
  {
    session.service("ALMemory").then(function (memory) 
    {
        memory.raiseEvent(id, value).then(function (result)
        {      
        }, function (error) 
            {
                console.log("An error occurred: " + error);
            });
    })
  }
      
      
  // get anything (bad)
  $scope.getMagic  = function(id) 
  {
    session.service("ALDialog").then(function (memory) 
    {
     
        console.log("magic" + id)
        memory.magicGet(id).then(function (result) 
        {
		  console.log("result magic" + result);
         	  $scope.$apply(function () 
                  {
                     //return "aa";
			         $scope.Dialogyes  = result;
                  });
            
        }, function (error) 
            {
                console.log("An error occurred: " + error);
            });
    })
  }
  
  
  
  
  
// allow to click with voice
session.service("ALMemory").then(function (ALMemory) {
    ALMemory.subscriber("Dialog/Click").then(function (subscriber) {
    subscriber.signal.connect(function (state) { 
    var xyz = document.getElementsByClassName("qichat");
    if (xyz.length!=0)
    {
        xyz[0].value="click!";
        xyz[0].click();
        
    }
     
    });
  });
});

 // class qichat that allow to clic
  var xyz = document.getElementsByClassName("qichat");
    if (xyz.length!=0)
    {
        var mList = [xyz[0].value];
            /*session.service("ALDialog").then(function (dialog) 
            {
              var mList = [xyz[0].value];
              dialog.setConcept("any","enu", mList).then(function (result)
              {
		              
         
               }, function (error) 
            {
                console.log("An error occurred: " + error);
            });
    })*/
  }
        //xyz[0].value="red";  
    else
        console.log("No class qichat element")
         // make the first one red
  //

  //$scope.getMagic("yes")
}]);
