super_mega_topico = (
    'topic: ~basicoConv()\n'
    'language: spe\n'
    'concept:(saludos) [Hola buenas saludos "Muy buenos dias" "Buen dia"]\n'
    'concept:(respuestas_simples) [si no "tal vez"]\n'
    'concept:(emociones_positivos) ["bien feliz alegre sonriente animado chevere "]\n'
    'concept:(emociones_negativas) [mal fatal terrible horrible aburrido triste desanimado]\n'
    'concept: (emociones_positivas) [feliz alegre alegria genial bacano bacana chevere rico] \n'
    'concept: (emociones_tristes) [triste tristeza achantado dolor mal melancolia melancolico aburrido miedo] \n'
    'concept: (emociones_enojo) [ira enojo piedra molestia rabia molesto molesta joda jode jodes mamado mamada quiero azare ] \n'
    'concept: (emociones_normales) [Bien bueno ok alegra agradable "como quiera" nada normal] \n'
    'concept: (bloque_uno_feliz) [feliz alegre emocionado chevere animado animada emocionada contento contenta] \n'
    'concept: (bloque_dos_feliz) [alegria felicidad esperanza emocion gratitud serenidad diversion] \n'
    'concept: (bloque_tres_feliz) [amor orgullo ] \n'
    'concept: (bloque_uno_triste) [aburrido cansado fastidiado mamado] \n'
    'concept: (bloque_dos_triste) [mal terrible horrible] \n'
    'concept: (bloque_tres_triste) [triste melancolica melancolico adolorido dolido ] \n'
    'concept: (bloque_cuatro_triste ) [tristeza melancolia ] \n'
    'concept: (bloque_uno_ira) [molesto emputado enojado jodido fastidiado mamado mamada] \n'
    'concept: (bloque_dos_ira) [piedra rabia ira furia colera] \n'
    'concept: (bloque_uno_normal) [bueno "ah bueno" okey "Esta bien" ] \n'
    'concept: (bloque_dos_normal) ["todo bien" "Esta agradable" "Me siento bien" bien "Esta Bueno"] \n'
    'concept: (bloque_tres_normal) ["me alegra" "Estoy normal" ] \n'
    'concept: (generos) [clasica jazz soul blues flamenco tango pop house rock punk metal disco] \n' 
    
    
    'u: (como se encuentra?) Me encuentro muy bien, muchas gracias, que tal se encuentra usted?\n'
    'u: (_~saludos) Muy buenos dias! Espero que se encuentre muy bien. Que quiere hacer hoy?  .\n'
    'u: ({Hoy} {"Este dia"} Quiero escuchar musica) De acuerdo, que genero quisieras escuchar?\n'
    'u: ([Vallenato Reggaeton Champeta Salsa Balada]) Con mucho gusto, ahorita lo pondremos\n'
    'u: (Di la verdad) Leon tiene cabeza de kiwi\n'
    'u: (Dime algo) Tengo una vaca lechera, no es una vaca cualquiera\n'
    'u: (Que se dice) Que se narra? la mojarrra\n'
    'u: (Mafe me cae mal) A mi tambien\n'
    'u: (Estoy cansado) Callese, perro\n'
    'u: (Canta porfavor) Guatermelon shugar...high, Guatermelon shugar...high\n'
    'u: (Chiste)La foca le dice a su mama: I lof llu, moder foca.\n'
    'u: (Mafe es facil) La Mafacil, le dicen\n'
    'u: (Mafe no me quiere) A nadie, solo se quiere a si misma\n'
    
    'u: ({"Imaginese que"}[Estoy "Me siento" ]{super}{mega}{re}{"re contra"} _~bloque_uno_feliz) Verte tan alegre te hace lucir genial, te ves muy bien hoy! \n'
    'u: ([Siento Tengo] {[mucha muchisima tantisima demasiada]} _~bloque_dos_feliz) La alegria te da una sonrisa muy hermosa \n'
    'u: ([Siento Tengo] {[mucho muchisimo tantisimo demasiado]} _~bloque_tres_feliz) Esos son los sentimientos mas hermosos de una persona \n'
    
    'u: ({"Imaginese que"}[Estoy "Me siento" ]{super}{mega}{re}{"re contra"} _~bloque_uno_triste) Que lastima, quisiera poder hacer algo para hacerte sentir mejor, Que tal una cancion? \n'
    'u: ({"Imaginese que"}[Estoy "Me siento" ]{super}{mega}{re}{"re contra"} _~bloque_dos_triste) Aca estoy para ayudarte con eso, esos sentimientos nos ayudan a sanar heridas\n'
    'u: ({"Imaginese que"}[Estoy "Me siento" ]{super}{mega}{re}{"re contra"} _~bloque_tres_triste) Tranquilo, todo pasara. Recuerda que pronto volveras a estar bien y seras mucho mejor \n'
    'u: ([Siento Tengo] {[mucha muchisima tantisima demasiada]} _~bloque_cuatro_triste) Te comprendo, pero piensa que podras verte a ti mismo de otra manera y saldras adelante mucho mejor\n'
    
    'u: ([Estoy "Me siento" ]{super}{mega}{re}{"re contra"} _~bloque_uno) Que lastima, quisiera poder hacer algo para hacerte sentir mejor, Que tal una cancion? \n'
    'u: ([Siento Tengo] {[mucha muchisima tantisima demasiada]} _~bloque_dos) Entiendo que te sientas asi, pero si no te     \n'
    'u: ([Vayase Vete]) Esta bien nos vemos luego \n'

    'u: (_~bloque_uno_normal) Me alegra, no hay nada como sentirse bien\n'
    'u: (_~bloque_dos_normal) Que bueno escuchar eso! Yo me alegro por ti\n'
    'u: (_~bloque_tres_normal) Eso esta de lujo\n'

    'u: (hablar sobre musica) Te gusta la musica? \n'
        'u1: (si) Enserio? Que genero te gusta escuchar?\n'
            'u2: (Vallenato) A mi tambien me gusta mucho el vallenato, te gusta diomedez?\n'
                'u3: (si) Es muy bueno! Escuchemos una cancion de el\n'
                'u3: (no) Entonces escuchemos musica vallenata variada.\n'
            'u2: (Reggaeton) A mi tambien me gusta mucho el reggaeton, te gusta Bad Bunny?\n'
                'u3: (si) Es muy bueno! Escuchemos una cancion de el\n'
                'u3: (no) Entonces escuchemos reggaeton variado.\n'
            'u2: (Salsa) A mi tambien me gusta mucho la salsa, te gusta el Joe Arroyo?\n'
                'u3: (si) Es muy bueno! Escuchemos una cancion de el\n'
                'u3: (no) Entonces escuchemos una buena salsa variada.\n'
            'u2: (Balada) A mi tambien me gusta mucho el reggaeton, te gusta Ricardo Montaner?\n'
                'u3: (si) Es muy bueno! Escuchemos una cancion de el\n'
                'u3: (no) Entonces escuchemos unas baladas variadas.\n'
            'u2: (Llanera) A mi tambien me gusta mucho el reggaeton, te gusta Reynaldo Armas?\n'
                'u3: (si) Es muy bueno! Escuchemos una cancion de el\n'
                'u3: (no) Entonces escuchemos musica llanera variada.\n'
            'u2: (_~generos) No conozco mucho de ese genero, que te gusta mas de ese genero?\n'
        'u1: (No) Que triste, creo que me deberia ir \n'
)
