topic_content_1 = ('topic: ~ejemploSimple()\n'
                   'language: spe\n'
                   'concept:(saludos) [Hola buenas saludos "Buenos dias" "Buen dia"]\n'
                   'concept:(respuestas_simples) [si no "tal vez"]\n'
                   'concept:(emociones_positivos) ["bien feliz alegre sonriente animado chevere "]\n'
                   'concept:(emociones_negativas) [mal fatal terrible horrible aburrido triste desanimado]\n'
                   'u: (como se encuentra?) Me encuentro muy bien, muchas gracias, que tal se encuentra usted?\n'
                   'u: (_~saludos) Muy buenos dias! Espero que se encuentre muy bien. Que quiere hacer hoy?  .\n'
                   'u: ({Hoy} {"Este dia"} Quiero escuchar musica) De acuerdo, que genero quisieras escuchar?\n'
                   'u: ([Vallenato Reggaeton Champeta Salsa Balada]) Con mucho gusto, ahorita lo pondremos\n'
                   'u: (Di la verdad) Leon tiene cabeza de kiwi\n'
                   'u: (Dime algo) Tengo una vaca lecheraaaa, no es una vaca cualquieraaaaaa\n'
                   'u: (Que te narras) Que se narra? la mojarra'
                   )
