/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulocuidador;

import BDInterface.RESPwABDInterface;
import ResPwAEntities.Cuidador;
import java.awt.CardLayout;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Persistence;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.persistence.Persistence;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author mafeg
 */
public class CuidadorStartPage extends javax.swing.JFrame {

    /**
     * Creates new form FinalBases
     */
    public CuidadorStartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroCui = new javax.swing.JPanel();
        regisCommit = new javax.swing.JButton();
        padre = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        nusuario = new javax.swing.JTextField();
        pwd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        menuGeneral = new javax.swing.JPanel();
        crearPerfil = new javax.swing.JButton();
        verPWAs = new javax.swing.JButton();
        cuento = new javax.swing.JPanel();
        consultarPwA = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        regisCommit.setText("Registrarse");

        javax.swing.GroupLayout registroCuiLayout = new javax.swing.GroupLayout(registroCui);
        registroCui.setLayout(registroCuiLayout);
        registroCuiLayout.setHorizontalGroup(
            registroCuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroCuiLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(regisCommit)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        registroCuiLayout.setVerticalGroup(
            registroCuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroCuiLayout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addComponent(regisCommit)
                .addGap(29, 29, 29))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        padre.setLayout(new java.awt.CardLayout());

        login.setText("Log In");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        nusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nusuarioActionPerformed(evt);
            }
        });

        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de Usuario");

        jLabel2.setText("Contraseña");

        jButton1.setLabel("Registrarse");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nusuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pwd)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                        .addGap(0, 248, Short.MAX_VALUE)
                        .addComponent(login)
                        .addGap(64, 64, 64))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(173, 173, 173))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(jButton1))
                .addGap(37, 37, 37))
        );

        padre.add(Home, "0");

        menuGeneral.setLayout(new java.awt.GridLayout(1, 0));

        crearPerfil.setLabel("Crear Nuevo PwA");
        crearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPerfilActionPerformed(evt);
            }
        });
        menuGeneral.add(crearPerfil);

        verPWAs.setText("Ver Pacientes");
        menuGeneral.add(verPWAs);

        padre.add(menuGeneral, "gMenu");
        menuGeneral.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout cuentoLayout = new javax.swing.GroupLayout(cuento);
        cuento.setLayout(cuentoLayout);
        cuentoLayout.setHorizontalGroup(
            cuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        cuentoLayout.setVerticalGroup(
            cuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        padre.add(cuento, "card4");

        javax.swing.GroupLayout consultarPwALayout = new javax.swing.GroupLayout(consultarPwA);
        consultarPwA.setLayout(consultarPwALayout);
        consultarPwALayout.setHorizontalGroup(
            consultarPwALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        consultarPwALayout.setVerticalGroup(
            consultarPwALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        padre.add(consultarPwA, "card5");

        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setLabel("Crear");

        jMenuItem1.setLabel("Cuento");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenu1.getAccessibleContext().setAccessibleDescription("");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(padre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(padre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("Mundial Rusia 2018");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    private void nusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nusuarioActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String cedula = null,user=null,pwdl=null;
        user=nusuario.getText();
        pwdl=pwd.getText();
        boolean loginl=false,sirve=true;
        Cuidador c=null;
        c=RESPwABDInterface.getCarer(user);
        if(user==null)
        {
            JOptionPane.showMessageDialog(null, "Ingrese su nombre de usuario");
            sirve=false;
        }
        if(sirve && pwdl==null)
        {
            JOptionPane.showMessageDialog(null, "Ingrese una contraseña");
            sirve=false;
        }

        if(sirve && c==null)
        {
            JOptionPane.showMessageDialog(null, "Nombre de Usuario inexistente");
        }else{
            loginl= c.getContraseña().equals(pwdl);
            if(!loginl)
            {
                JOptionPane.showMessageDialog(null, "Constraseña no ooincide");
            }else{
                        CardLayout card = (CardLayout) padre.getLayout();
                        card.show(padre, "gMenu");     

            }
        }

    }//GEN-LAST:event_loginActionPerformed

    private void crearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        JFrame.setDefaultLookAndFeelDecorated(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.SubstanceTwilightLookAndFeel");

                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    System.out.println("Substance Graphite failed to initialize");
                }
                CuidadorStartPage w = new CuidadorStartPage();
                w.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel consultarPwA;
    private javax.swing.JButton crearPerfil;
    private javax.swing.JPanel cuento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton login;
    private javax.swing.JPanel menuGeneral;
    private javax.swing.JTextField nusuario;
    private javax.swing.JPanel padre;
    private javax.swing.JTextField pwd;
    private javax.swing.JButton regisCommit;
    private javax.swing.JPanel registroCui;
    private javax.swing.JButton verPWAs;
    // End of variables declaration//GEN-END:variables
}
