/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulocuidador;

import BDInterface.RESPwABDInterface;
import ResPwAEntities.Cuidador;
import java.awt.CardLayout;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Persistence;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.persistence.Persistence;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author mafeg
 */
public class CuidadorStartPage extends javax.swing.JFrame {

    public static String emf= "moduloCuidadorPU";
    /**
     * Creates new form FinalBases
     */
    public CuidadorStartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroCui = new javax.swing.JPanel();
        regisCommit = new javax.swing.JButton();
        padre = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        nusuario = new javax.swing.JTextField();
        pwd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        menuGeneral = new javax.swing.JPanel();
        crearPerfil = new javax.swing.JButton();
        verPWAs = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        regisCommit.setText("Registrarse");

        javax.swing.GroupLayout registroCuiLayout = new javax.swing.GroupLayout(registroCui);
        registroCui.setLayout(registroCuiLayout);
        registroCuiLayout.setHorizontalGroup(
            registroCuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroCuiLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(regisCommit)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        registroCuiLayout.setVerticalGroup(
            registroCuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroCuiLayout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addComponent(regisCommit)
                .addGap(29, 29, 29))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        padre.setLayout(new java.awt.CardLayout());

        login.setText("Log In");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        nusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nusuarioActionPerformed(evt);
            }
        });

        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de Usuario");

        jLabel2.setText("Contraseña");

        jButton1.setLabel("Registrarse");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nusuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pwd)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                        .addGap(0, 248, Short.MAX_VALUE)
                        .addComponent(login)
                        .addGap(64, 64, 64))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(173, 173, 173))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(jButton1))
                .addGap(37, 37, 37))
        );

        padre.add(Home, "0");

        menuGeneral.setLayout(new java.awt.GridLayout());

        crearPerfil.setLabel("Crear Nuevo PwA");
        crearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPerfilActionPerformed(evt);
            }
        });
        menuGeneral.add(crearPerfil);

        verPWAs.setText("Ver Pacientes");
        menuGeneral.add(verPWAs);

        padre.add(menuGeneral, "gMenu");
        menuGeneral.getAccessibleContext().setAccessibleName("");

        jMenuBar1.setRequestFocusEnabled(false);

        jMenu4.setText("Inicio");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Inicio");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Registrar");

        jMenuItem1.setText("Encuentro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenu1.getAccessibleContext().setAccessibleDescription("");

        jMenu2.setText("Generar");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Partidos 2nda Fase");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Venta");

        jMenuItem3.setText("Boleteria");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(padre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(padre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("Mundial Rusia 2018");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
//
//        Calendar c = Calendar.getInstance();
//        fechal.setText("Fecha Actual: \t " + String.valueOf(c.get(Calendar.DATE)) + "-" + String.valueOf(c.get(Calendar.MONTH)) + "-" + String.valueOf(c.get(Calendar.YEAR)));
//        String curr = String.format("%02d:%02d", c.get(Calendar.HOUR), c.get(Calendar.MINUTE));
//        horal.setText("Hora Actual: \t " + curr);
//        Vector<String> enc = new Vector<String>();
//        Vector<Vector<Object>> cont = new Vector<Vector<Object>>();
//        enc.add("Partido");
//        enc.add("Fecha");
//        enc.add("Estadio");
//        enc.add("Ciudad");
//        enc.add("Equipos");
//        enc.add("Horario");
//        List<Partidos> p = f.obtenerPartidos();
//        for (Partidos aux : p) {
//            Date t = (Date) aux.getHorario();
//            Date n = Calendar.getInstance().getTime();
//            if (t.after(n)) {
//                Calendar x = Calendar.getInstance();
//                x.setTime(t);
//                Vector<Object> o = new Vector<Object>();
//                o.add(aux.getCodigopartido());
//                String curry = String.format("%02d:%02d", x.get(Calendar.HOUR), x.get(Calendar.MINUTE));
//                o.add(String.valueOf(x.get(Calendar.DATE)) + "-" + String.valueOf(x.get(Calendar.MONTH)) + "-" + String.valueOf(x.get(Calendar.YEAR)));
//                o.add(aux.getCodestadio().getNombree());
//                o.add(aux.getCodestadio().getCiudad());
//                String s = new String(aux.getLocal().getNombreeq() + "-" + aux.getVisitante().getNombreeq());
//                o.add(s);
//                o.add(curry);
//                cont.add(o);
//            }
//        }
//        tablaDis = new JTable(cont, enc);
//        jScrollPane6.setViewportView(tablaDis);
//        CardLayout card = (CardLayout) padre.getLayout();
//        card.show(padre, "7");        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
//        fase.removeAllItems();
//        List<Fase> fa = f.obtenerFases();
//        for (Fase q : fa) {
//            fase.addItem(q);
//        }
//        CardLayout card = (CardLayout) padre.getLayout();
//        card.show(padre, "4");

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CardLayout card = (CardLayout) padre.getLayout();
        card.show(padre, "0");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    private void nusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nusuarioActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String cedula = null,user=null,pwdl=null;
        user=nusuario.getText();
        pwdl=pwd.getText();
        boolean loginl=false,sirve=true;
        Cuidador c=null;
        c=RESPwABDInterface.getCarer(user);
        if(user==null)
        {
            JOptionPane.showMessageDialog(null, "Ingrese su nombre de usuario");
            sirve=false;
        }
        if(sirve && pwdl==null)
        {
            JOptionPane.showMessageDialog(null, "Ingrese una contraseña");
            sirve=false;
        }

        if(sirve && c==null)
        {
            JOptionPane.showMessageDialog(null, "Nombre de Usuario inexistente");
        }else{
            loginl= c.getContraseña().equals(pwdl);
            if(!loginl)
            {
                JOptionPane.showMessageDialog(null, "Constraseña no ooincide");
            }else{
                        CardLayout card = (CardLayout) padre.getLayout();
                        card.show(padre, "gMenu");     

            }
        }

    }//GEN-LAST:event_loginActionPerformed

    private void crearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        JFrame.setDefaultLookAndFeelDecorated(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.SubstanceTwilightLookAndFeel");

                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    System.out.println("Substance Graphite failed to initialize");
                }
                CuidadorStartPage w = new CuidadorStartPage();
                w.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JButton crearPerfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JButton login;
    private javax.swing.JPanel menuGeneral;
    private javax.swing.JTextField nusuario;
    private javax.swing.JPanel padre;
    private javax.swing.JTextField pwd;
    private javax.swing.JButton regisCommit;
    private javax.swing.JPanel registroCui;
    private javax.swing.JButton verPWAs;
    // End of variables declaration//GEN-END:variables
}
